### ISSUE TITLE
FunctionCalls

### ISSUE THREAD

**Issue by bebnev-pro** [willhlaw/firestore-security-tests#4]
Hello, thanks for your repository. functionMocks works well, but as i understood it just test call that returns test data. Can i use "live" calls to my workable firestore DB and check some data or some "live" access?

**Comment by willhlaw** [comment]
@ipbebnev, no. "Live" calls are not implemented, though there does seem to be a path in which it can be done. See https://github.com/willhlaw/firestore-security-tests/issues/2#issuecomment-355350365.
