### ISSUE TITLE
Imprevements to the console output

### ISSUE THREAD

**Issue by compojoom** [willhlaw/firestore-security-tests#7]
I've started writing tests for our current set of firestore rules as we are planning some updates to them and I want to make sure that we can figure out when something breaks. 

I've written around 10 tests right now and I personally see a problem and I'm wondering if I'm missing something.

The toString method says passed success -> Allow/deny or failure ... Then all this is followed by a json string with auth, path and method.

You kind of can make your way around, but it's very hard. 
I can test the same path for different things. What I think would help is to have a description of the tested rule. 
I'm thinking of something like jest or mocha where you say test('1+2 to equal 3') or it('1+2 should equal 3')
and then in the console you see exactly what you are testing... 

@willhlaw - what do you think? Would you approve such a pull request?

**Comment by willhlaw** [comment]
@compojoom sounds like a good idea.
